trigger:
  branches:
    include:
    - master
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
      displayName: Install Node.js
    - task: CmdLine@2
      displayName: npm install and build
      inputs:
        script: >
          npm install -g @angular/cli

          npm install

          ng build --configuration production --output-path=dist-prod
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/dist-prod
        includeRootFolder: false
        replaceExistingArchive: true
        archiveFile: $(Build.ArtifactStagingDirectory)/Angular_archive.zip
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)/Angular_archive.zip

